### ISSUE TITLE
After using PlayerView Podfile, there appear downcast problem

### ISSUE THREAD

**Issue by SuYungCheng** [davidlondono/PlayerView#3]
Before I installed PlayerView, I have only one Podfile "AWSS3" ,Podfile  looks like that:
- source 'https://github.com/CocoaPods/Specs.git'
- platform :ios, '8.0'
- pod 'AWSS3'

And it has "no error",

After install PlaerView , Podfile  looks like that:
- source 'https://github.com/CocoaPods/Specs.git'
- platform :ios, '8.0'
- pod 'AWSS3'
- use_frameworks!
- pod 'PlayerView'

Here comes many Downcast problems.
And remove PlayerView, It comes normally again.
How can I build succeed with PlayerView?

**Comment by davidlondono** [comment]
can you post where did you get the error? code or image

**Comment by SuYungCheng** [comment]
Before install Pic
http://imgur.com/Lry4kqg

After install Pic
http://imgur.com/USyv1yz

**Comment by davidlondono** [comment]
i dont really know if there is something with your code, you have a variable with type "String!?", but still my pod doesn't change any off the class string or the enum Optional

**Comment by SuYungCheng** [comment]
Thank you for your help,After I use Carthage.It works very well.
I think it's only my project problem.
Sincerely.
